function zeigeAchtung () {
    dunkelRot = neopixel.rgb(0, 204, 0)
    hellRot = neopixel.rgb(130, 0, 0)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(2, dunkelRot)
    strip.setPixelColor(3, dunkelRot)
    strip.setPixelColor(4, dunkelRot)
    strip.setPixelColor(5, dunkelRot)
    strip.setPixelColor(9, dunkelRot)
    strip.setPixelColor(14, dunkelRot)
    strip.setPixelColor(16, dunkelRot)
    strip.setPixelColor(23, dunkelRot)
    strip.setPixelColor(24, dunkelRot)
    strip.setPixelColor(31, dunkelRot)
    strip.setPixelColor(32, dunkelRot)
    strip.setPixelColor(39, dunkelRot)
    strip.setPixelColor(40, dunkelRot)
    strip.setPixelColor(47, dunkelRot)
    strip.setPixelColor(49, dunkelRot)
    strip.setPixelColor(54, dunkelRot)
    strip.setPixelColor(58, dunkelRot)
    strip.setPixelColor(59, dunkelRot)
    strip.setPixelColor(60, dunkelRot)
    strip.setPixelColor(61, dunkelRot)
    strip.setPixelColor(19, hellRot)
    strip.setPixelColor(20, hellRot)
    strip.setPixelColor(27, hellRot)
    strip.setPixelColor(28, hellRot)
    strip.setPixelColor(35, hellRot)
    strip.setPixelColor(36, hellRot)
    strip.setPixelColor(51, hellRot)
    strip.setPixelColor(52, hellRot)
}
function zeigeSmiley () {
    zeile1 = neopixel.rgb(225, 0, 0)
    zeile2 = neopixel.rgb(252, 144, 3)
    zeile3 = neopixel.rgb(53, 252, 3)
    zeile4 = neopixel.rgb(255, 211, 3)
    zeile5 = neopixel.rgb(4, 122, 31)
    zeile6 = neopixel.rgb(0, 229, 225)
    zeile7 = neopixel.rgb(0, 13, 255)
    zeile8 = neopixel.rgb(255, 0, 255)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(0, zeile1)
    strip.setPixelColor(1, zeile1)
    strip.setPixelColor(2, zeile1)
    strip.setPixelColor(3, zeile1)
    strip.setPixelColor(4, zeile1)
    strip.setPixelColor(5, zeile1)
    strip.setPixelColor(6, zeile1)
    strip.setPixelColor(7, zeile1)
    strip.setPixelColor(8, zeile2)
    strip.setPixelColor(9, zeile2)
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(11, zeile2)
    strip.setPixelColor(12, zeile2)
    strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(14, zeile2)
    strip.setPixelColor(15, zeile2)
    strip.setPixelColor(16, zeile3)
    strip.setPixelColor(17, zeile3)
    strip.setPixelColor(18, zeile3)
    strip.setPixelColor(19, zeile3)
    strip.setPixelColor(20, zeile3)
    strip.setPixelColor(21, zeile3)
    strip.setPixelColor(22, zeile3)
    strip.setPixelColor(23, zeile3)
    strip.setPixelColor(24, zeile4)
    strip.setPixelColor(25, zeile4)
    strip.setPixelColor(26, zeile4)
    strip.setPixelColor(27, zeile4)
    strip.setPixelColor(28, zeile4)
    strip.setPixelColor(29, zeile4)
    strip.setPixelColor(30, zeile4)
    strip.setPixelColor(31, zeile4)
    strip.setPixelColor(32, zeile5)
    strip.setPixelColor(33, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(34, zeile5)
    strip.setPixelColor(35, zeile5)
    strip.setPixelColor(36, zeile5)
    strip.setPixelColor(37, zeile5)
    strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(39, zeile5)
    strip.setPixelColor(40, zeile6)
    strip.setPixelColor(41, zeile6)
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(43, zeile6)
    strip.setPixelColor(44, zeile6)
    strip.setPixelColor(45, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(46, zeile6)
    strip.setPixelColor(47, zeile6)
    strip.setPixelColor(48, zeile7)
    strip.setPixelColor(49, zeile7)
    strip.setPixelColor(50, zeile7)
    strip.setPixelColor(51, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(53, zeile7)
    strip.setPixelColor(54, zeile7)
    strip.setPixelColor(55, zeile7)
    strip.setPixelColor(56, zeile8)
    strip.setPixelColor(57, zeile8)
    strip.setPixelColor(58, zeile8)
    strip.setPixelColor(59, zeile8)
    strip.setPixelColor(60, zeile8)
    strip.setPixelColor(61, zeile8)
    strip.setPixelColor(62, zeile8)
    strip.setPixelColor(63, zeile8)
}
let Lichtsensor = 0
let zeile8 = 0
let zeile7 = 0
let zeile6 = 0
let zeile5 = 0
let zeile4 = 0
let zeile3 = 0
let zeile2 = 0
let zeile1 = 0
let hellRot = 0
let dunkelRot = 0
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P0, 128, NeoPixelMode.RGB)
basic.forever(function () {
    while (true) {
        pins.digitalWritePin(DigitalPin.P3, 1)
        basic.pause(1)
        Lichtsensor = pins.analogReadPin(AnalogReadWritePin.P2)
        pins.digitalWritePin(DigitalPin.P3, 0)
        basic.showNumber(Lichtsensor)
    }
    while (true) {
        zeigeAchtung()
        strip.show()
        basic.pause(500)
        zeigeSmiley()
        strip.show()
        basic.pause(500)
    }
    for (let index = 0; index < 9; index++) {
        for (let index2 = 0; index2 <= 63; index2++) {
            strip.setPixelColor(64 + index2, neopixel.colors(NeoPixelColors.Red))
            strip.show()
            basic.pause(500)
        }
        strip.showColor(neopixel.colors(NeoPixelColors.Purple))
        basic.pause(200)
        basic.showString("Stop")
        basic.pause(100)
    }
})
